/** Shape of `public/data/dashboard.json`, generated by `scripts/build_dashboard_data.py`. */

export type Severity = 'LOW' | 'WATCH' | 'MODERATE' | 'HIGH' | 'VERY HIGH'

export type TrajectoryState = 'STABLE' | 'EMERGING' | 'ESCALATING' | 'RAPIDLY ESCALATING'

export type Confidence = 'LOW' | 'MEDIUM' | 'HIGH'

export interface DeviatingSignal {
  /** Human label, e.g. "Class participation". */
  signal: string
  /** Directional z-score against the student's own 4-week baseline. */
  z: number
  /** Non-linear 0-100 risk derived from that z-score. */
  risk: number
  /** True when z >= 2.5. */
  strong: boolean
}

export interface SignalOnset {
  signal: string
  label: string
  week: number
}

export interface WeekPoint {
  week: number
  risk: number
  /** 3-week rolling mean of `risk`. */
  rolling: number
  severity: Severity
  velocity: number
  trajectory: TrajectoryState
  phase?: string
  /** How many independent signals deviated that week. */
  signals: number
  isFirstDeviation: boolean
  cascadeActive?: boolean
  timelineEvent?: string
  measurements?: Record<string, number>
}

export interface TrajectoryEvent {
  studentId: string
  week: number
  type: string
  label: string
  description: string
}

export interface SignalTransition {
  fromSignal: string
  fromLabel: string
  toSignal: string
  toLabel: string
  studentCount: number
  meanLagWeeks: number
  medianLagWeeks: number
}

export interface HeatmapPoint {
  studentId: string
  week: number
  signal: string
  label: string
  z: number
  risk: number
  deviation: boolean
}

export interface Student {
  id: string
  name?: string
  mentorName?: string
  parentName?: string
  rank: number
  /** Week-9 behavioural change score, 0-100. Not a diagnosis. */
  risk: number
  severity: Severity
  trajectory: TrajectoryState
  velocity: number
  acceleration: number
  anomaly: number
  confidence: Confidence
  signalCount: number
  /** Week the first meaningful deviation was detected, or -1 for none. */
  firstDeviationWeek: number
  earliestSignal: string
  detectionType: string
  leadTimeWeeks: number
  weeksAboveWatch: number
  weeksAboveModerate: number
  weeksAboveHigh: number
  contributors: string[]
  explanation: string
  phase?: string
  cascadeStartWeek?: number
  cascadeEndWeek?: number
  cascadeDuration?: number
  cascadeDepth?: number
  leadingSignal?: string
  secondSignal?: string
  convergenceWeek?: number
  convergenceStrength?: number
  earlyWarningWindow?: number
  signalOnsetOrder?: SignalOnset[]
  whyNow?: string
  /** Current-week deviations, highest z-score first. */
  signals: DeviatingSignal[]
  weeks: WeekPoint[]
}

export interface DashboardData {
  generatedFrom: string
  currentWeek: number
  baselineWeeks: number
  studentCount: number
  students: Student[]
  events?: TrajectoryEvent[]
  transitions?: SignalTransition[]
  heatmap?: HeatmapPoint[]
}

/** Normalised 0-1 band used for the priority tier summary. */
export type PriorityTier = 'high' | 'medium' | 'low'

/** A request a student sent from the mobile app (POST /support/requests). */
export interface StudentRequest {
  id: string
  type: string
  message: string
  createdAt: string
  status: 'new' | 'reviewing' | 'closed'
  sessionId?: string
}
